// Records fullscreen video of each screen for the length of its narration clip.
// Run after: vite dev server (apps/web) + storybook dev server are both up,
// and audio/*.mp3 have been generated by generate-audio.sh.
//
// Usage: node capture.mjs
// Env overrides: VITE_URL (default http://localhost:5173), SB_URL (default http://localhost:6006)
import { chromium } from "playwright";
import { execSync } from "node:child_process";
import { mkdirSync, readdirSync, renameSync, rmSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { pathToFileURL } from "node:url";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const VIEWPORT = { width: 1920, height: 1080 };
const VITE = process.env.VITE_URL ?? "http://localhost:5173";
const SLIDES = pathToFileURL(join(HERE, "slides.html")).href;

const AUDIO_DIR = join(HERE, "audio");
const OUT_DIR = join(HERE, "video");

// name -> url. Duration is read from the matching audio/<name>.mp3 file (+2s buffer)
// rather than hardcoded, so re-recording after editing narration.txt stays in sync.
const screens = [
  ["01-home", `${VITE}/`],
  ["02-onboarding", `${VITE}/?editStart=1`],
  ["03-journey", `${VITE}/?skipHome=1`],
  ["04-cards", `${VITE}/?skipHome=1`],
  ["05-codex", `${SLIDES}#codex`],
  ["06-gpt", `${SLIDES}#gpt`],
  ["07-closing", `${VITE}/`],
];

function audioDurationSeconds(mp3Path) {
  const out = execSync(`ffmpeg -i "${mp3Path}" -hide_banner 2>&1 || true`).toString();
  const match = out.match(/Duration: (\d+):(\d+):([\d.]+)/);
  if (!match) throw new Error(`Could not read duration of ${mp3Path}`);
  const [, h, m, s] = match;
  return Number(h) * 3600 + Number(m) * 60 + Number(s);
}

mkdirSync(OUT_DIR, { recursive: true });
const browser = await chromium.launch();

for (const [name, url] of screens) {
  const mp3 = join(AUDIO_DIR, `${name}.mp3`);
  if (!existsSync(mp3)) throw new Error(`Missing ${mp3} — run generate-audio.sh first`);
  const seconds = audioDurationSeconds(mp3) + 2; // +2s buffer, trimmed off in mux.sh

  const tmpDir = join(OUT_DIR, `tmp-${name}`);
  mkdirSync(tmpDir, { recursive: true });

  const context = await browser.newContext({
    viewport: VIEWPORT,
    recordVideo: { dir: tmpDir, size: VIEWPORT },
  });
  const page = await context.newPage();
  console.log(`[${name}] loading ${url} (recording ${seconds.toFixed(1)}s)`);
  await page.goto(url, { waitUntil: "networkidle" });
  await page.waitForTimeout(seconds * 1000);
  await context.close(); // finalizes the video file

  const [file] = readdirSync(tmpDir);
  const finalPath = join(OUT_DIR, `${name}.webm`);
  renameSync(join(tmpDir, file), finalPath);
  rmSync(tmpDir, { recursive: true, force: true });
  console.log(`[${name}] saved -> ${finalPath}`);
}

await browser.close();
console.log("done");
